#!/bin/bash

#Author: Tong Chhin
#Author email: tongchhin@csu.fullerton.edu

#Program name: Chemistry.c


echo "Remove un-needed files, if any exist."
rm *.o
rm *.out

echo "Compile the C main function chemistry.c according to C standard of year 2020"
gcc -c -Wall -std=c2x -o chemistry.o -m64 -no-pie -fno-pie chemistry.c

echo "Link object files"
gcc -m64 -std=c2x chemistry.o -fno-pie -no-pie -o runprogram.out

echo "Run the program \"Text file I/O\""
./runprogram.out

echo "The bash file has terminated."
